# раздел содержит информацию относительно настроек биржы
[exchange]
# имя биржи, записывается в сообщениях, которые отправляет данный шлюз
name = "binance"

# настройки аккаунта
[account]
api_key = "Q0LPrj20sAGqptchS8ZiR2kJzUggr5W3CZVRxIRzB8Nr1OSgbXivjF62YVE0E98e"
secret_key = "V9fu4jT21mzejk0sdq3jutubN6xxLMvBtY6ZKRJYXb3kNlYMJfoeTxXG8qDweRek"

# от куда получаем информацию о торгуемых монетах
[coins]

# настройки транспортного уровня
[aeron]
    # Настройки относящиеся к отправке данных
    [aeron.publishers]
        # настройки канала для publishers рассылающего market data
        # ["aeron:udp?control=172.31.14.205:40456|control-mode=dynamic", 111]
        # или
        # ["aeron:ipc", 111]

#        orderbook = ["aeron:udp?control=172.31.14.205:40456|control-mode=dynamic", 111]
        orderbook = ["aeron:ipc", 100]
        # настройки publishers осуществляющего отправку баланса
        #        balance = ["aeron:ipc", 111]
        balance = ["aeron:ipc", 101]

        # настройки publishers осуществляющего отправку логов
        # ["channel", channel_id]
#        logs = ["aeron:udp?endpoint=54.248.171.18:20121", 1001]
        logs = ["aeron:ipc", 102]
    # Настройки относящиеся к приему данных.
    [aeron.subscribers]
        # канал в котором приходят команды от ядра.
        # ["aeron:ipc", 111]
#        core = ["aeron:udp?endpoint=54.248.171.18:20121", 555]
        core = ["aeron:ipc", 103]