#ifndef BINANCECONNECTOR_CONFIG_H
#define BINANCECONNECTOR_CONFIG_H


#define API_KEY 		"Q0LPrj20sAGqptchS8ZiR2kJzUggr5W3CZVRxIRzB8Nr1OSgbXivjF62YVE0E98e"
#define SECRET_KEY		"V9fu4jT21mzejk0sdq3jutubN6xxLMvBtY6ZKRJYXb3kNlYMJfoeTxXG8qDweRek"

#endif //BINANCECONNECTOR_CONFIG_H
